@startuml sequence__users_login
hide footbox
skinparam actorStyle awesome
!theme aws-orange
skinparam backgroundcolor White
title Sequence | Users : Login


System -> System : Checks if the person is not connected
Visitor -> Visitor : Fills in the form correctly
Visitor -> System : Click on "Se connecter"
System -> System : Checks the values of the form
System -> System : Logs the user into the site
System --> Visitor : Displays a confirmation message
@enduml